history_records/urls.py
from django.conf.urls import url
# import views
from history_records import views

urlpatterns = [
    url(r'^(?P<username>[\w]+)/$', views.index, name='system_home'),
    # url(r'^show$',views.show,name='show_history')
    url(r'^(?P<username>[\w]+)/(?P<file_id>\d+)/$', views.medical_file, name='medical_file'),
    url(r'^(?P<username>[\w]+)/(?P<file_id>[\d]+)/medical_history$', views.medical_history, name='medical_history'),
    url(r'^(?P<username>[\w]+)/(?P<file_id>[\d]+)/progress_notes$', views.progress_notes, name='progress_notes'),
    url(r'^(?P<username>[\w]+)/(?P<file_id>[\d]+)/physician_orders$', views.physician_orders, name='phycisian_orders'),
    url(r'^(?P<username>[\w]+)/(?P<file_id>[\d]+)/unit_summary$', views.unit_summary, name='unit_summary'),
    url(r'^(?P<username>[\w]+)/create_file$', views.create_medical_file, name='create_medical_file'),
    url(r'^(?P<username>[\w]+)/create_file_index$', views.create_file, name='create_medical_file_index'),
]

hospital-albretch/urls.py
from django.conf.urls import include, url

from django.contrib import admin

from . import views

import hello.views

admin.autodiscover()

# Examples:
# url(r'^$', 'hospital-albretch.views.home', name='home'),
# url(r'^blog/', include('blog.urls')),

urlpatterns = [
    url(r'hospital/', include('hospital.urls')),
    url(r'^patient/', include('patient.urls', namespace='patient_app')),
    url(r'^rec/', include('receptionist.urls', namespace='rec_app')),
    url(r'history/', include('history_records.urls', namespace='history_records')),
    # url(r'^$', hello.views.index, name='index'),
    url(r'^db', hello.views.db, name='db'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.firstpage, name='firstpage'),
    url(r'^SystemHomePage/', views.systemhomepage, name='systemhomepage'),
    url(r'^PatientSearch/', views.patientsearch, name='patientsearch'),
    url(r'^login_all/', views.login, name='login_all'),
    url(r'^logout/', views.logout, name='logout'),
    url(r'^reports/', views.get_reports, name='reports'),
    url(r'^physician/', include('physician.urls', namespace='doc_app')),
    url(r'^messages/', include('django_messages.urls', namespace='django_messages')),
    url(r'^mostrar/', include('schedule.urls', namespace='mostrar')),
]

patient/urls.py
from django.conf.urls import url
from patient import views

urlpatterns = [
    url(r'^register$', views.register, name='patient_register'),
    url(r'^home$', views.home, name='patient_home'),
]

physician/urls.py
from django.conf.urls import url
from physician import views

urlpatterns = [
    url(r'^register$', views.register, name='doc_register'),
    url(r'^home$', views.home, name='doc_home'),
    url(r'^doc_search$', views.doc_search, name='doc_search'),
    # url(r'^download$',views.download,name='download'),
]

schedule/urls.py
from django.conf.urls import url

from schedule import views

urlpatterns = [
    url(r'^calendario$', views.calendar, name='calendario'),
]

templates/_includes/header.html
{% load static %}
<div class="row">

    <!-- Profile Info and Notifications -->
    <div class="col-md-6 col-sm-8 clearfix">

        <ul class="list-inline links-list pull-left pull-none-xsm">

            <!-- Profile Info -->
            <li class="profile-info dropdown"><!-- add class "pull-right" if you want to place this from right -->

                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <i class="entypo-user"></i>&nbsp;{{ request.user.get_full_name }}
                </a>

                <ul class="dropdown-menu">

                    <!-- Reverse Caret -->
                    <li class="caret"></li>

                    <!-- Profile sub-links -->
                    <li>
                        <a href="extra-timeline.html">
                            <i class="entypo-user"></i>
                            Edit Profile
                        </a>
                    </li>

                    <li>
                        <a href="mailbox.html">
                            <i class="entypo-mail"></i>
                            Inbox
                        </a>
                    </li>

                    <li>
                        <a href="extra-calendar.html">
                            <i class="entypo-calendar"></i>
                            Calendar
                        </a>
                    </li>

                    <li>
                        <a href="#">
                            <i class="entypo-clipboard"></i>
                            Tasks
                        </a>
                    </li>
                </ul>
            </li>

        </ul>


    </div>


    <!-- Raw Links -->
    <div class="col-md-6 col-sm-4 clearfix hidden-xs">

        <ul class="list-inline links-list pull-right">
            <li>
                <a href="{% url 'logout' %}">
                    Cerrar Sesión <i class="entypo-logout right"></i>
                </a>
            </li>
        </ul>

    </div>

</div>

templates/_includes/sidebar.html
{% load static %}
<div class="sidebar-menu">

    <div class="sidebar-menu-inner">

        <header class="logo-env">

            <!-- logo -->
            <div class="logo">
                <a href="{% url 'systemhomepage' %}">
                    <h4 style="color: white;">
                        <strong>HOSPITAL ALBRETCH</strong>
                    </h4>
{#                    <img src="{% static 'images/albretch/logo.png' %}" width="100" alt="" />#}
                </a>
            </div>

            <!-- logo collapse icon -->
            <div class="sidebar-collapse">
                <a href="#" class="sidebar-collapse-icon"><!-- add class "with-animation" if you want sidebar to have animation during expanding/collapsing transition -->
                    <i class="entypo-menu"></i>
                </a>
            </div>


            <!-- open/close menu icon (do not remove if you want to enable menu on mobile devices) -->
            <div class="sidebar-mobile-menu visible-xs">
                <a href="#" class="with-animation"><!-- add class "with-animation" to support animation -->
                    <i class="entypo-menu"></i>
                </a>
            </div>

        </header>


        <ul id="main-menu" class="main-menu">
            <!-- add class "multiple-expanded" to allow multiple submenus to open -->
            <!-- class "auto-inherit-active-class" will automatically add "active" class for parent elements who are marked already with class "active" -->
            <li>
                <a href="{% if doc %}{% url 'doc_app:doc_home' %}{% else %}{% url 'patient_app:patient_home' %}{% endif %}">
                    <i class="entypo-gauge"></i>
                    <span class="title">Dashboard</span>
                </a>
            </li>
            {% if patient %}
                <li>
                    <a href="{% if patient %}{% url 'history_records:medical_history' patient.user.username 1 %}{% endif %}">
                        <i class="entypo-list"></i>
                        <span class="title">Historia Clínica</span>
                    </a>
                </li>
            {% endif %}
            {% if doc %}
                <li>
                    <a href="{% if doc %}{% url 'mostrar:calendario' %}{% endif %}">
                        <i class="entypo-list"></i>
                        <span class="title">Calendario</span>
                    </a>
                </li>
            {% endif %}
        </ul>

    </div>

</div>